### ISSUE TITLE
D.R.Y problem

### ISSUE THREAD

**Issue by ShaharAriel** [Motty-dev/JBH-Project#1]
https://github.com/Motty-dev/JBH-Project/blob/d946e59b11185472a900346a3487e64d83b095a1/csv.c#L27

Please make the function shorter something like:
```c

typedef int (*validation_func)(char *field);
validation_func func[] = {is_valid_name, is_valid_last, is_valid_id, is_valid_phone, ...};

int parse_input(char *str)
{
    char *field = strtok(",", str);
    int field_num = 0;  
    while (field)
    {
        if(!func[field_num++](field))
        {
            return 0;
        }
        field = strtok(",", NULL);
    }
    return 1;
}

```

**Comment by Motty-dev** [comment]
תיקנתי את ההערות שלך בהתאם למה שדיברנו, כמו כן קיצרתי את הפונקציה המדוברת
(ביותר מ 50%).
השינויים כוללים את שמות הקבצים החדשים, טיפול ביציאה מהmain, קיצור הקוד,
המספרים הוחלפו בmacro.
דחפתי את השינויים ושני הבראנצ׳ים מעודכנים. (מירג׳ג׳תי את שני הcommits
האחרונים לתוך מאסטר גם, היו קצת קונפליקטים שסידרתי).

בתאריך יום ו׳, 17 בפבר׳ 2023 ב-12:11 מאת ShaharAriel <
***@***.***>:
